arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.1
  kinematics_solver_attempts: 10
  position_only_ik: False
  allow_approximate_ik: False